### ISSUE TITLE
dfn in F test is not dynamic

### ISSUE THREAD

**Issue by bstuddard** [jkclem/chowtest#2]
I believe the dfn=5 in the cumulative f test should be a dynamic input rather than hardcoded equal to 5.  

https://github.com/jkclem/chowtest/blob/f73f185dadcbb14e567ce65f942e6c8bdb432d4d/chowtest/__init__.py#L90

**Comment by Hercroce** [comment]
You're right, I used this code in one of my projects and that was one of the modifications I had to make.

If you are dealing with regressions made with historical series, you can make the following change:

`p_value = 1 - f.cdf(Chow_Stat, dfn = k, dfd = (N1 + N2 - 2 * k)) `

**Comment by jkclem** [comment]
@bstuddard and @Hercroce Sorry I am fixing this several years too late, but it is fixed now.
